---
title: "p8105_hw2_xc2472"
author: "Xing Chen"
date: 2019-10-1
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```


# Problem 1

## Mr. Trash Wheel dataset

```{r}
trash_wheel = 
  read_excel(path = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = "Mr. Trash Wheel", 
             range = "A2:N408")

trash_wheel = janitor::clean_names(trash_wheel)

trash_wheel = drop_na(trash_wheel, dumpster)

trash_wheel = mutate(trash_wheel, 
  sports_balls = round(sports_balls, digits = 0),
  sports_balls = as.integer(sports_balls)
)
```


## The precipitation dataset

import the datasets

```{r}
weather17_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>% 
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather18_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2018-01-01",
                      date_max = "2018-12-31") %>% 
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

omit rows without precipitation data and add a variable year

```{r}
weather17_df = drop_na(weather17_df, prcp)

weather17_df = mutate(weather17_df, year = 2017)

weather18_df = drop_na(weather18_df, prcp)

weather18_df = mutate(weather18_df, year = 2018)
```






